[meta]
name = "Nitro Dashboard"
author = "NitroQuery"
category = "Overlay"
siteid = 102
version = "1.4.0"
blocks = [ "Plugin_NitroDashboard" ]
# perms = "paid"

[game]
min_version = "2022-04-14"
# max_version = "2021-06-03"

[script]
dependencies = [ "VehicleState" ]
imports = [ "Icons.as" ]
