[meta]
name = "Nitro Dashboard"
author = "NitroQuery"
category = "Overlay"
siteid = 102
version = "1.4.1"
blocks = [ "Plugin_NitroDashboard" ]
# perms = "paid"

[game]
min_version = "2022-05-19"

[script]
dependencies = [ "VehicleState" ]
imports = [ "Icons.as" ]
